# Generated by Django 6.0.6 on 2026-06-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_remove_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('department', models.CharField(choices=[('hr', 'human resource'), ('acc', 'accounting'), ('mgt', 'management'), ('it', 'information & technology')], max_length=50, null=True)),
                ('salary', models.PositiveIntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(choices=[('clothing', 'clothing'), ('electronics', 'electronics'), ('sports', 'sports')], max_length=100, null=True)),
                ('price', models.FloatField(null=True)),
                ('quantity', models.PositiveIntegerField(default=1, null=True)),
                ('total', models.FloatField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255, null=True)),
                ('roll_number', models.CharField(max_length=8, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('course', models.CharField(max_length=255, null=True)),
                ('year', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], max_length=5, null=True)),
                ('semester', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd')], max_length=5, null=True)),
            ],
        ),
    ]
