# Generated by Django 6.0.6 on 2026-06-16 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_employee_product_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
